### ISSUE TITLE
Crash when clicking the right Voices arrow in the track editor panel

### ISSUE THREAD

**Issue by Bombe** [vsariola/sointu#62]
I have no idea what else might be relevant so I’mma just leave this stacktrace here. Running on an M1 MacBookPro, macOS 11.3, go version go1.16.3 darwin/arm64.

```
panic: runtime error: index out of range [0] with length 0

goroutine 50 [running]:
github.com/vsariola/sointu/tracker/gioui.(*TrackEditor).layoutTracks(0x140001a5040, 0x8d5, 0x2d8, 0x8d5, 0x2d8, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/Software/sointu/tracker/gioui/trackeditor.go:332 +0x1fd4
github.com/vsariola/sointu/tracker/gioui.(*TrackEditor).Layout.func2.2.1(0x8d5, 0x2d8, 0x8d5, 0x2d8, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, 0x104e338c0, ...)
	/Users/bombe/Software/sointu/tracker/gioui/trackeditor.go:289 +0x4c
gioui.org/layout.Flex.Layout(0x4000000, 0x907, 0x2d8, 0x907, 0x2d8, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/go/pkg/mod/gioui.org@v0.0.0-20210410094005-495c69018772/layout/flex.go:134 +0x6d0
github.com/vsariola/sointu/tracker/gioui.(*TrackEditor).Layout.func2.2(0x907, 0x2d8, 0x907, 0x2d8, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, 0x104e338c0, ...)
	/Users/bombe/Software/sointu/tracker/gioui/trackeditor.go:286 +0x14c
gioui.org/layout.Flex.Layout(0x4000001, 0x907, 0x320, 0x907, 0x320, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/go/pkg/mod/gioui.org@v0.0.0-20210410094005-495c69018772/layout/flex.go:134 +0x6d0
github.com/vsariola/sointu/tracker/gioui.(*TrackEditor).Layout.func2(0x907, 0x320, 0x907, 0x320, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, 0x104e338c0, ...)
	/Users/bombe/Software/sointu/tracker/gio:281 +0x1c8
gioui.org/layout.Inset.Layout(0x0, 0x0, 0x0, 0x0, 0x907, 0x320, 0x907, 0x320, 0x4000000040000000, 0x104a77f68, ...)
	/Users/bombe/go/pkg/mod/gioui.org@v0.0.0-20210410094005-495c69018772/layout/layout.go:147 +0x2c0
github.com/vsariola/sointu/tracker/gioui.Surface.Layout.func2(...)
	/Users/bombe/Software/sointu/tracker/gioui/surface.go:39
github.com/vsariola/sointu/tracker/gioui.Surface.Layout(0x18, 0x0, 0x0, 0x0, 0x0, 0x100, 0x907, 0x320, 0x907, 0x320, ...)
	/Users/bombe/Software/sointu/tracker/gioui/surface.go:50 +0x2b0
github.com/vsariola/sointu/tracker/gioui.(*TrackEditor).Layout(0x140001a5040, 0x907, 0x320, 0x907, 0x320, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/Software/sointu/tracker/gioui/trackeditor.go:280 +0x73c
github.com/vsariola/sointu/tracker/gioui.(*Tracker).layoutBottom.func2(0x907, 0x320, 0x907, 0x320, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, 0x104e338c0, ...)
	/Users/bombe/Software/sointu/tracker/gioui/layout.go:128 +0x4c
github.com/vsariola/sointu/tracker/gioui.(*Split).Layout(0x1400019c048, 0xb48, 0x320, 0xb48, 0x320, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/Software/sointu/tracker/gioui/split.go:138 +0x490
github.com/vsariola/sointu/tracker/gioui.(*Tracker).layoutBottom(0x140001c0000, 0xb48, 0x320, 0xb48, 0x320, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/Software/sointu/tracker/gioui/layout.go:123 +0x80
github.com/vsariola/sointu/tracker/gioui.(*Split).Layout(0x1400019c060, 0xb48, 0x754, 0xb48, 0x754, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/Software/sointu/tracker/gioui/split.go:138 +0x490
github.com/vsariola/sointu/tracker/gioui.(*Tracker).Layout(0x140001c0000, 0xb48, 0x754, 0xb48, 0x754, 0x4000000040000000, 0x104a77f68, 0x140001a0090, 0xc01d898bfb6d0340, 0x5e64a426c08a, ...)
	/Users/bombe/Software/sointu/tracker/gioui/layout.go:18 +0x188
github.com/vsariola/sointu/tracker/gioui.(*Tracker).Run(0x140001c0000, 0x140001a0000, 0x104a788a8, 0x104e61978)
	/Users/bombe/Software/sointu/tracker/gioui/run.go:57 +0x1e8
github.com/vsariola/sointu/tracker/gioui.Main.func1(0x104a7a688, 0x14000226180, 0x104a788a8, 0x104e61978, 0x0)
	/Users/bombe/Software/sointu/tracker/gioui/run.go:75 +0x108
created by github.com/vsariola/sointu/tracker/gioui.Main
	/Users/bombe/Software/sointu/tracker/gioui/run.go:68 +0x5c
```

**Comment by Bombe** [comment]
```
bombe@vanadium sointu % git rev-parse HEAD
d5f413c5dc101c852d3c05c5ae83dda50453588b
```

**Comment by vsariola** [comment]
Pushing fix now.
